### PR TITLE
Add websocket support

### PR DESCRIPTION
**Pull request by bdraco**
Motion and doorbell updates should now happen
right away

Reduces the amount of entity updates since we
now only update cameras that change when we
poll instead of them all.

Fixes https://github.com/briis/unifiprotect/issues/97

Requires https://github.com/briis/pyunifiprotect/pull/6
Thanks to @hjdhjd for decoding the protocol

### CODE REVIEW

**Comment by bdraco** [comment]
Looks like I've introduced a bug in unloading.  Marking it as a draft to fix that

**Comment by bdraco** [comment]
All fixed. Verified I could add and remove the integration without error and it disconnects the websocket

**Comment by briis** [comment]
THANK YOU. I will update the manifest to work with the updated pyunifiprotect 0.21.0

**Comment by briis** [comment]
When running the new version, motion detection works perfectly, but I get the following error when trying to change the recording mode from the Switch. Basically all the Switches fail with the same error:

```python
'UnifiProtectData' object has no attribute 'async_request_refresh'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/homeassistant/components/websocket_api/commands.py", line 138, in handle_call_service
    await hass.services.async_call(
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1408, in async_call
    task.result()
  File "/usr/lib/python3.8/site-packages/homeassistant/core.py", line 1443, in _execute_service
    await handler.job.target(service_call)
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 470, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/entity.py", line 664, in async_request_call
    await coro
  File "/usr/lib/python3.8/site-packages/homeassistant/helpers/service.py", line 507, in _handle_entity_call
    await result
  File "/config/custom_components/unifiprotect/switch.py", line 142, in async_turn_on
    await self.protect_data.async_request_refresh()
AttributeError: 'UnifiProtectData' object has no attribute 'async_request_refresh'
````

**Comment by bdraco** [comment]
I missed updating the method.  I'll send a PR in a moment to fix it

**Comment by briis** [comment]
The fix removed the error, but the switches don't work. They flip for a second and then return to previous state - and the state does not change. I tested the Service itself, from the developer menu, and that works. And when doing it from here, the Switch also changes to the correct position. Any ideas?

**Comment by bdraco** [comment]
For me the switches are updating but since there camera update isn't ready yet they don't change state for 60 seconds.

I'm working on improving that now

**Comment by briis** [comment]
You are right - there is a delay, but it works. I was a bit impatient
