### ISSUE TITLE
Cannot load integration after updating from 0.9.1 to 0.10.1

### ISSUE THREAD

**Issue by curt7000** [briis/unifiprotect#364]
### Home Assistant Version?

2021.11.5

### UniFi Protect Version?

1.20.0

### UniFi Protect HA Integration version?

0.10.1

### What happened?

Integration will not load after upgrading from 0.9.1 to 0.10.1

All is working great on 0.9.1.

Is there a Python 3.9+ dependency?

### Relevant log output

```shell
Logger: homeassistant.setup
Source: setup.py:178 
First occurred: 12:55:02 PM (1 occurrences) 
Last logged: 12:55:02 PM

Setup failed for unifiprotect: Unable to import component: cannot import name 'SHAPE_DICT' from 'pydantic.fields' (/srv/homeassistant/lib/python3.8/site-packages/pydantic/fields.cpython-38-x86_64-linux-gnu.so)
```

**Comment by AngellusMortis** [comment]
3.9 _should_ not be a requirement, we run tests for `pyunifiprotect` on python 3.8, 3.9 and 3.10. 

Can you post the full stacktrace so I can try to reproduce?

**Comment by curt7000** [comment]
I'm sorry, how should/can I pull the stack trace you are looking for?

**Comment by AngellusMortis** [comment]
Click the "Load Full Home Assistant Log" button at the bottom of the logs page, look for the error the stack trace should appear in the logs. Example (from the IoTaWatt integration):

```
2021-11-29 02:03:36 ERROR (MainThread) [iotawattpy.connection] Err:
2021-11-29 02:03:36 ERROR (MainThread) [homeassistant.components.iotawatt.coordinator] Unexpected error fetching IoTaWatt data: 'NoneType' object has no attribute 'text'
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
self.data = await self._async_update_data()
File "/usr/src/homeassistant/homeassistant/components/iotawatt/coordinator.py", line 65, in _async_update_data
await self.api.update(lastUpdate=self._last_run)
File "/usr/local/lib/python3.9/site-packages/iotawattpy/iotawatt.py", line 76, in update
await self._refreshSensors(timespan, lastUpdate)
File "/usr/local/lib/python3.9/site-packages/iotawattpy/iotawatt.py", line 154, in _refreshSensors
results = response.text
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by borjaburgos** [comment]
Also running into issues with this upgrade. Here're my logs:

```
Logger: homeassistant.config_entries
Source: custom_components/unifiprotect/__init__.py:124 
Integration: Unifi Protect (documentation, issues) 
First occurred: 3:39:06 PM (1 occurrences) 
Last logged: 3:39:06 PM

Error setting up entry UDMPRO for unifiprotect
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 293, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/unifiprotect/__init__.py", line 108, in async_setup_entry
    await _async_get_or_create_nvr_device_in_registry(hass, entry, nvr_info)
  File "/config/custom_components/unifiprotect/__init__.py", line 124, in _async_get_or_create_nvr_device_in_registry
    device_registry.async_get_or_create(
TypeError: async_get_or_create() got an unexpected keyword argument 'configuration_url'
```

**Comment by AngellusMortis** [comment]
@borjaburgos Unrelated. You need to upgrade HA to 2021.11 or downgrade Protect to 1.19.x and the integration to 0.9.1. The 0.10.x version of the integration requires HA 2021.11+ and Protect 1.20+

**Comment by borjaburgos** [comment]
Thank you. Will try that. Sorry for the noise on this issue, my bad.

**Comment by curt7000** [comment]
Changed Logger to DEBUG, but cannot find anything else, except the snippet I provided earlier. :(

**Comment by AngellusMortis** [comment]
Are you using the virtualenv install method? If so and it looks like you are on the latest stable version, it should be rather easy to migrate to Home Assistant container install instead of using the virtualenv one. Then that will get you Python 3.9 right away. Moving away from a virtualenv install will save you a lot of headaches.

https://www.home-assistant.io/installation/linux#install-home-assistant-container

Just point `-v /PATH_TO_YOUR_CONFIG:/config \` to your existing Home Assistant config folder.

**Comment by curt7000** [comment]
Unfortunately, I have some other dependencies and need to stay in a venv.
I’ve upgraded Python in the past, will give it a go tomorrow to see if this
does anything.

When I try to upgrade to 0.10.1, the integration does not load and I cannot
delete it.  Removing the integration first, upgrading, and then attempting
to configure the integration after a restart results in Unable to load
Config.

**Comment by kristianolofsson** [comment]
Any progress with bug? Let me know if you need any assistance

**Comment by AngellusMortis** [comment]
No progress and there will likely not be much if any. Python 3.8 support is deprecated for Home Assistant and will be removed in version 2022.1 (releases in ~1 month).

The best solution is to upgrade to Python 3.9.

**Comment by kristianolofsson** [comment]
Sure! I'm running HA 2021.11.5 based on Py 3.9. Can we expect a solution on 3.9 or waiting for 3.10?

**Comment by AngellusMortis** [comment]
Are you having this _same exact_ error and everything? The one that @curt7000 was having looks like it was related to running Python 3.8, but I never got a full stack trace. If you are getting the same exception message as OP, can you post a stack trace? Otherwise, please open a separate issue.

**Comment by kristianolofsson** [comment]
Running protect version 1.20.0, HA 2121.11.5 and this compenent version 0.10.1

`This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/unifiprotect/config_flow.py:63 
Integration: Unifi Protect (documentation, issues) 
First occurred: 4:30:58 PM (3 occurrences) 
Last logged: 4:38:29 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 138, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 246, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 320, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/unifiprotect/config_flow.py", line 63, in async_step_user
    server_info = await unifiprotect.server_information()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 117, in server_information
    return await self._get_server_info()
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/unifi_protect_server.py", line 128, in _get_server_info
    data = await self.api_request_obj("bootstrap")
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 238, in api_request_obj
    data = await self.api_request(
  File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 226, in api_request
    json_data: Union[List[Any], Dict[str, Any]] = pjson.loads(data)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

`

**Comment by AngellusMortis** [comment]
Couple of things:

Is this a new issue? Did you have it before you upgraded or is the first time you installed the integration?

Is the user you made for HA...
   * A Local User (_not_ an Ubiquiti Cloud SSO account)?
   * A "Limited Admin" with the role "Administrator"? The "View" role may also work, but if you have any Viewports you may have issues with your viewports. If you use any other custom role, you may have permissions configured in an unexpected manner.

**Comment by kristianolofsson** [comment]
Yes, local user with admin right created and yes it worked before. After upgrade the stream disappeared and deleted the integration. I now can't add it again wo getting this error.

**Comment by AngellusMortis** [comment]
Your error is indicative that UniFi Protect is not giving back a response at all. What kind of device are you running UniFi Protect on?

Other than that, perhaps try the 0.11-beta to see if it resolves you issue.

**Comment by nowjon** [comment]
HA Version: 2021.12.3
Protect Version: 1.22.2
I've tried both the version 0.10.1 and version 11 beta 5, neither work

Here's the log from the Log Details, let me know if theres something else I can try

2021-12-17 12:16:19 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
resp = await request_handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
resp = await handler(request)
File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
return await handler(request)
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
result = await result
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 157, in post
return await super().post(request, flow_id)
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
result = await method(view, request, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 252, in async_configure
result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
File "/config/custom_components/unifiprotect/config_flow.py", line 155, in async_step_user
nvr_data, errors = await self._async_get_nvr_data(user_input)
File "/config/custom_components/unifiprotect/config_flow.py", line 96, in _async_get_nvr_data
nvr_data = await protect.get_nvr()
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 791, in get_nvr
data = await self.api_request_obj("nvr")
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 248, in api_request_obj
data = await self.api_request(
File "/usr/local/lib/python3.9/site-packages/pyunifiprotect/api.py", line 236, in api_request
json_data: Union[List[Any], Dict[str, Any]] = pjson.loads(data)
File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by AngellusMortis** [comment]
> Protect Version: 1.22.2

Protect 1.22.2 is not a valid version of protect. The newest version is currently 1.20.1.

Some questions though:

* Is this a new setup? Or were you using 0.9 previously?

If not:
* What UniFi OS Console do you have? What is the firmware version of that?
* Are you using a Local Admin user with the correct permissions? We have only really tested everything with a user that had read/write access to most things (the "Administrator" role).
* Is Protect fully set up and working? Can you go to `https://<proxy_ip>/proxy/protect/api/nvr` and make sure it is returning something?

**Comment by curt7000** [comment]
Apologies for taking this long to come back, but I can confirm that moving to Python 3.9 resolves the issue!

**Comment by AngellusMortis** [comment]
Thanks for verifying. I am going to go ahead and close then. py3.8 is very close to EOL'd for Home Assistant anyways. Recommendation for anyone else would probably be to stay on 0.9 until you can go to py3.9.
